name = "proxy-saml"

main = "./index.js"

account_id = "ca7271d81a89aa1b584684f4aea8c1a4"
workers_dev = true
compatibility_date = "2021-11-15"

route = "https://passwordless.atko.rocks/sso/saml2/0oa46js4ppH3bpwYG1d7"

[vars]
ORIGIN = ""
new_location = "https://identity-broadc0m.atko.rocks/login/callback?connection="
